complex/urls.py
from django.urls import include, path

import complex.views as complex_views

urlpatterns = (
    path('complex-search', complex_views.ComplexSearchView.as_view(), name='complex-search'),
    path('complex-document-view/<int:dataset_id>/<document_es_id>/',
         complex_views.ComplexDocumentView.as_view(), name='complex-document-view'),
)

gdw/urls.py
from django.contrib import admin
from django.urls import include, path

import core.views as core_views

urlpatterns = [
    path('', core_views.MainPageView.as_view(), name='home'),
    path('core/', include('core.urls')),
    path('complex/', include('complex.urls')),
    path('mendelian/', include('mendelian.urls')),
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
]

genesysv/urls.py
from django.contrib import admin
from django.urls import include, path

import core.views as core_views

urlpatterns = [
    path('', core_views.MainPageView.as_view(), name='home'),
    path('core/', include('core.urls')),
    path('complex/', include('complex.urls')),
    path('mendelian/', include('mendelian.urls')),
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
]

complex/models.py
from django.db import models

# Create your models here.

core/models.py
import json

from django.contrib.auth.models import Group, User
from django.db import models
from sortedm2m.fields import SortedManyToManyField

from common.models import TimeStampedModel
from core.utils import flush_memcache


class AppName(TimeStampedModel):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name


class AnalysisType(TimeStampedModel):
    name = models.CharField(max_length=64)
    app_name = models.ForeignKey(
        'AppName',
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


class ESFilterType(TimeStampedModel):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name


class FormType(TimeStampedModel):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name


class WidgetType(TimeStampedModel):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name


class Study(TimeStampedModel):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255, blank=True)

    class Meta:
        unique_together = ('name', 'description',)
        verbose_name_plural = 'studies'

    def __str__(self):
        return self.name


class Dataset(TimeStampedModel):
    study = models.ForeignKey('Study', on_delete=models.CASCADE)
    analysis_type = models.ManyToManyField(AnalysisType, blank=True)
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    es_index_name = models.CharField(max_length=255)
    es_type_name = models.CharField(max_length=255)
    es_host = models.CharField(max_length=255)
    es_port = models.CharField(max_length=255)
    is_public = models.BooleanField(default=False)
    allowed_groups = models.ManyToManyField(Group, blank=True)

    class Meta:
        unique_together = ('name', 'description',)

    def __str__(self):
        return self.name


class SearchOptions(TimeStampedModel):
    dataset = models.OneToOneField(
        'Dataset',
        on_delete=models.CASCADE,
    )
    es_terminate = models.BooleanField(default=True)
    es_terminate_size_per_shard = models.IntegerField(default=80)
    maximum_table_size = models.IntegerField(default=400)

    class Meta:
        verbose_name_plural = 'Search Options'


class FilterField(TimeStampedModel):
    dataset = models.ForeignKey(
        'Dataset',
        on_delete=models.CASCADE,
    )
    display_text = models.CharField(max_length=255)
    in_line_tooltip = models.CharField(max_length=255, blank=True)
    tooltip = models.CharField(max_length=255, blank=True)
    default_value = models.CharField(max_length=255, blank=True)
    form_type = models.ForeignKey(
        'FormType',
        on_delete=models.CASCADE,
    )
    widget_type = models.ForeignKey(
        'WidgetType',
        on_delete=models.CASCADE,
    )
    es_name = models.CharField(max_length=255)
    path = models.CharField(max_length=255, blank=True)
    es_data_type = models.CharField(max_length=255)
    es_text_analyzer = models.CharField(max_length=255, blank=True)
    es_filter_type = models.ForeignKey(
        'ESFilterType',
        on_delete=models.CASCADE,
    )
    # Did not make place_in_panel a foreign key because that would lead to a circular
    # relationship. But I still need the panel name to get the admin interface to filter
    # correctly.
    place_in_panel = models.CharField(max_length=255)
    is_visible = models.BooleanField(default=True)

    class Meta:
        unique_together = ('dataset', 'es_name',
                           'es_filter_type', 'form_type', 'widget_type')

    def save(self, *args, **kwargs):
        flush_memcache()
        super(FilterField, self).save(*args, **kwargs)

    def __str__(self):
        return "%s %s" % (self.display_text, self.in_line_tooltip)


class FilterFieldChoice(TimeStampedModel):
    filter_field = models.ForeignKey(
        'FilterField',
        on_delete=models.CASCADE,
    )
    value = models.CharField(max_length=255)

    class Meta:
        unique_together = ('filter_field', 'value',)

    def save(self, *args, **kwargs):
        flush_memcache()
        super(FilterFieldChoice, self).save(*args, **kwargs)

    def __str__(self):
        return self.value


class AttributeField(TimeStampedModel):
    dataset = models.ForeignKey(
        'Dataset',
        on_delete=models.CASCADE,
    )
    display_text = models.CharField(max_length=255)
    es_name = models.CharField(max_length=255)
    path = models.CharField(max_length=255, null=True, blank=True)
    place_in_panel = models.CharField(max_length=255)
    is_visible = models.BooleanField(default=True)
    is_link_field = models.BooleanField(default=False)

    class Meta:
        unique_together = ('dataset', 'es_name', 'path')

    def save(self, *args, **kwargs):
        flush_memcache()
        super(AttributeField, self).save(*args, **kwargs)

    def __str__(self):
        return "%s" % (self.display_text)


class FilterPanel(TimeStampedModel):
    dataset = models.ForeignKey(
        'Dataset',
        on_delete=models.CASCADE,
    )
    name = models.CharField(max_length=255)
    are_sub_panels_mutually_exclusive = models.BooleanField(default=False)
    filter_fields = SortedManyToManyField(FilterField, blank=True)
    is_visible = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        flush_memcache()
        super(FilterPanel, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class FilterSubPanel(TimeStampedModel):
    dataset = models.ForeignKey(
        'Dataset',
        on_delete=models.CASCADE,
    )
    filter_panel = models.ForeignKey(
        'FilterPanel',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    name = models.CharField(max_length=255)
    filter_fields = SortedManyToManyField(FilterField, blank=True)
    is_visible = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        flush_memcache()
        super(FilterSubPanel, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class FilterTab(TimeStampedModel):
    dataset = models.ForeignKey(
        'Dataset',
        on_delete=models.CASCADE,
    )
    name = models.CharField(max_length=255)
    filter_panels = SortedManyToManyField(FilterPanel, blank=True)

    def save(self, *args, **kwargs):
        flush_memcache()
        super(FilterTab, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class AttributePanel(TimeStampedModel):
    dataset = models.ForeignKey(
        'Dataset',
        on_delete=models.CASCADE,
    )
    name = models.CharField(max_length=255)
    are_sub_panels_mutually_exclusive = models.BooleanField(default=False)
    attribute_fields = SortedManyToManyField(AttributeField, blank=True)
    is_visible = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        flush_memcache()
        super(AttributePanel, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class AttributeSubPanel(TimeStampedModel):
    dataset = models.ForeignKey(
        'Dataset',
        on_delete=models.CASCADE,
    )
    attribute_panel = models.ForeignKey(
        'AttributePanel',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    name = models.CharField(max_length=255)
    attribute_fields = SortedManyToManyField(AttributeField, blank=True)
    is_visible = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        flush_memcache()
        super(AttributeSubPanel, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class AttributeTab(TimeStampedModel):
    dataset = models.ForeignKey(
        'Dataset',
        on_delete=models.CASCADE,
    )
    name = models.CharField(max_length=255)
    attribute_panels = SortedManyToManyField(AttributePanel, blank=True)

    def save(self, *args, **kwargs):
        flush_memcache()
        super(AttributeTab, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


REVIEW_STATUS_CHOICES = (
    ('Approved', 'Approved'),
    ('Rejected', 'Rejected'),
    ('Delete', 'Delete Status'),
)


class DocumentReview(TimeStampedModel):
    group = models.ForeignKey(
        Group,
        on_delete=models.CASCADE,
    )
    dataset = models.ForeignKey(
        'Dataset',
        on_delete=models.CASCADE,
    )
    document_es_id = models.CharField(max_length=64)
    description = models.CharField(max_length=64, blank=True, null=True)
    status = models.CharField(max_length=16, choices=REVIEW_STATUS_CHOICES)

    def __str__(self):
        return self.document_es_id


class DocumentReviewHistory(TimeStampedModel):
    document_review_status = models.ForeignKey(
        'DocumentReview',
        on_delete=models.CASCADE,
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    status = models.CharField(max_length=16, choices=REVIEW_STATUS_CHOICES)

    class Meta:
        verbose_name_plural = 'Document review status history'


class SearchLog(TimeStampedModel):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True, blank=True
    )
    dataset = models.ForeignKey(
        'Dataset',
        on_delete=models.CASCADE,
    )
    analysis_type = models.ForeignKey(
        'AnalysisType',
        on_delete=models.CASCADE,
    )
    header = models.TextField()
    query = models.TextField()
    nested_attribute_fields = models.TextField(null=True, blank=True)
    non_nested_attribute_fields = models.TextField(null=True, blank=True)
    filters_used = models.TextField(null=True, blank=True)
    attributes_selected = models.TextField()
    nested_attributes_selected = models.TextField(null=True, blank=True)
    non_nested_attributes_selected = models.TextField()

complex/views.py
from django.shortcuts import get_object_or_404

import core
from complex.utils import ComplexElasticsearchResponseParser


class ComplexSearchView(core.views.BaseSearchView):
    elasticsearch_response_parser_class = ComplexElasticsearchResponseParser

class ComplexDocumentView(core.views.BaseDocumentView):
    template_name = "complex/variant.html"

complex/templates/complex/variant.html
{% extends "base.html" %} {% load staticfiles %} {% load crispy_forms_tags %} {% load common_tags %} {% block title %} Variant {% endblock %} {% block content %}

<style>
/* width */
.panel ::-webkit-scrollbar {
    width: 15px;
}

/* Track */
.panel ::-webkit-scrollbar-track {
    box-shadow: inset 0 0 5px grey; 
    border-radius: 10px;
}
 
/* Handle */
.panel ::-webkit-scrollbar-thumb {
    background: #c5d5e5; 
    border-radius: 10px;
}

/* Handle on hover */
.panel ::-webkit-scrollbar-thumb:hover {
    background: #c5d5e5; 
}
</style>



<div class="row">
{% for panel in dataset_obj.attributetab_set.first.attribute_panels.all %} {% if panel.name != 'Sample Related Information' %}
{% if panel.attributesubpanel_set.all %}

{% for subpanel in panel.attributesubpanel_set.all %}
{% if subpanel.name in panels_with_values %}
<div class="col-md-4">
  <div class="panel panel-primary" style="min-height: 400px;">
    <div class="panel-heading">{{panel.name}} - {{subpanel.name}}</div>
    <div class="panel-body" style="max-height: 370px;overflow-y: auto;">
      <div class="table-responsive">
        <table class="table table-condensed" style="padding-bottom:-15px;">
          {% for subpanel_element in subpanel.attribute_fields.all %}
          {% if result|get_value_from_dict:subpanel_element.es_name %}
          <tr>
            <td><strong>{{subpanel_element.display_text}}</strong></td>
            <td>{{ result|get_value_from_dict:subpanel_element.es_name }}</td>
          </tr>
          {% endif %}
          {% endfor %}
        </table>
      </div>
    </div>
  </div>
</div>
{% endif %}
{% endfor %}


{% else %}
{% if panel.name in panels_with_values%}
<div class="col-md-4">
  <div class="panel panel-primary" style="min-height: 400px;" >
    <div class="panel-heading">{{panel.name}}</div>
    <div class="panel-body" style="max-height: 370px;overflow-y: auto;">
      <div class="table-responsive" style="padding-bottom:-15px;">
        <table class="table table-condensed" >
          {% for element in panel.attribute_fields.all %}
          {% if result|get_value_from_dict:element.es_name %}
          <tr>
            <td><strong>{{element.display_text}}</strong></td>
            <td>{{ result|get_value_from_dict:element.es_name }}</td>
          </tr>
          {% endif %}
          {% endfor %}
        </table>
      </div>
    </div>
  </div>
</div>
{% endif %}

{% endif %}

{% endif %} {% endfor %}
</div>

{% if result|get_value_from_dict:"CSQ_nested" %}
<div class="panel panel-primary">
  <div class="panel-heading">VEP CSQ Annotations</div>
  <div class="panel-body">
    {% for element in result.CSQ_nested %}
    <div class="col-md-4">
        <div class="panel panel-primary" >
          <div class="panel-body">
            <div class="table-responsive">
              <table class="table table-condensed">
                 {% for ele_key, ele_val in element.items|dictsort:"0.lower" %}
                <tr>
                  <td><strong>{{ele_key}}</strong></td>
                  <td>{{ele_val}}</td>
                </tr>
                      {% endfor %}
              </table>
            </div>
          </div>
        </div>
    </div>
      {% endfor %}

  </div>
</div>
{% endif %} 




<div class="panel panel-primary">
  <div class="panel-heading">Sample Information</div>
  <div class="panel-body">
    <div class="table-responsive">
      <table id="sample_table" class="table table-condensed">
        <thead>
          <tr>
            <th>AD_alt</th>
            <th>AD_ref</th>
            <th>DP</th>
            <th>Family_ID</th>
            <th>Father_Genotype</th>
            <th>Father_ID</th>
            <th>Father_Phenotype</th>
            <th>GQ</th>
            <th>GT</th>
            <th>Mother_Genotype</th>
            <th>Mother_ID</th>
            <th>Mother_Phenotype</th>
            <th>Phenotype</th>
            <th>PL</th>
            <th>Sample_ID</th>
            <th>Sex</th>
          </tr>
        </thead>
        <tbody>
          {% for element in result.sample %}
          <tr>
            <td>{{element.AD_alt}}</td>
            <td>{{element.AD_ref}}</td>
            <td>{{element.DP}}</td>
            <td>{{element.Family_ID}}</td>
            <td>{{element.Father_Genotype}}</td>
            <td>{{element.Father_ID}}</td>
            <td>{{element.Father_Phenotype}}</td>
            <td>{{element.GQ}}</td>
            <td>{{element.GT}}</td>
            <td>{{element.Mother_Genotype}}</td>
            <td>{{element.Mother_ID}}</td>
            <td>{{element.Mother_Phenotype}}</td>
            <td>{{element.Phenotype}}</td>
            <td>{{element.PL}}</td>
            <td>{{element.Sample_ID}}</td>
            <td>{{element.Sex}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>




<script>
    $(document).ready(function() {
        $('#sample_table').DataTable({
            "iDisplayLength": 10
        });
      });

</script>

{% endblock %}